# Name of the application
spring:
  application:
    name: library
  profiles:
    # The default profile is used when no active profile is set.
    active: test

  # Datasource configuration
  jpa:
    hibernate:
      # On Dev we rely on flyway to create the schema,
      # Hibernate should just validate it.
      ddl-auto: validate

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration

# application.yml
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE_PATH:/tmp/library-app.log}

# TODO: Change the datasource URL, username and password
app:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000 # 1 hour in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# Custom info
info:
  app:
    name: Library Management System
    description: A distributed library system
    version: 1.0.0

